#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := PCA9685.cpp abcLed.cpp assignLetterToLed.cpp abcMotor.cpp assignLetterToMotor.cpp colorSensor.cpp

# header files in this project
HEADERS := PCA9685.hpp abcLed.hpp assignLetterToLed.hpp abcMotor.hpp assignLetterToMotor.hpp colorSensor.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
